server.port=8085

# Render Database Connection
spring.datasource.url=jdbc:postgresql://dpg-d7obq78js32c73bofn90-a.oregon-postgres.render.com/food_db_xz9l
spring.datasource.username=food_db_xz9l_user
spring.datasource.password=jMQKTfOhbBZdqZxStqYpWGIhwHgurb7W
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.datasource.hikari.connection-timeout=30000